name: CI/CD Pipeline

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Set up Node.js 
        uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - name: Run tests
        run: echo "No tests defined"

      - name: Build Docker image
        run: docker build -t simple-node-app ./app  

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to DockerHub
        run: docker tag simple-node-app:latest ${{ secrets.DOCKER_USERNAME }}/simple-node-app:latest && docker push ${{ secrets.DOCKER_USERNAME }}/simple-node-app:latest
